import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import { fromBase64 } from './base64';

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.SHEET_CLIENT_EMAIL,
  key: fromBase64(process.env.SHEET_PRIVATE_KEY),
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});

export const doc = new GoogleSpreadsheet(process.env.SHEET_DOC_ID, serviceAccountAuth);